gitlabUrl: https://gitlab.com/
runnerRegistrationToken: "glrt-Qbf1lqaZ1UYSkIIEbvZ3K286MQpwOjEzbm5yMQp0OjMKdTpmZno4eRg.01.1j0bw4442"

runners:
  executor: "kubernetes"
  image: "partofaplan/custom-gitlab-runner:1.0.2"
  config: |
    [[runners]]
      name = "custom-k8s-runner"
      url = "https://gitlab.com/"
      token = "glrt-Qbf1lqaZ1UYSkIIEbvZ3K286MQpwOjEzbm5yMQp0OjMKdTpmZno4eRg.01.1j0bw4442"
      executor = "kubernetes"

      [runners.kubernetes]
        image = "partofaplan/custom-gitlab-runner:1.0.2"
        helper_image = "gitlab/gitlab-runner-helper:arm64-latest"
        namespace = "gitlab"
        volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/var/lib/docker:/var/lib/docker", "/Users/zachperkins/.kube:/root/.kube:ro"]
  arch: "arm64"

serviceAccount:
  create: false
  name: gitlab-runner 
  namespace: gitlab